[project]
name = 'News-Verification-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.crowd-fact-checking]
path = 'contracts/crowd-fact-checking.clar'
clarity_version = 3
epoch = '3.2'

[contracts.misinformation-flagging]
path = 'contracts/misinformation-flagging.clar'
clarity_version = 3
epoch = 'latest'

[contracts.source-credibility-oracle]
path = 'contracts/source-credibility-oracle.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
